---
new_page_extension: html
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: themes/hugo-theme-massively
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
