---
new_page_extension: html
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: themes/hugo-theme-massively
public_path: "/themes/hugo-theme-massively/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
